name: Add Kaomoji to Issue Comments

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  add-kaomoji:
    runs-on: ubuntu-latest
    steps:
      - name: Add Kaomoji
        uses: actions/github-script@v7
        with:
          script: |
            const kaomojis = ["(＾▽＾)", "(╯✧▽✧)╯", "٩(ˊᗜˋ*)و", "(•̀ᴗ•́)و"];
            const random = kaomojis[Math.floor(Math.random() * kaomojis.length)];
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${random}`
            });
